### ISSUE TITLE
Can use "useCallback" for optimized child components.

### ISSUE THREAD

**Issue by Colkadome** [NansD/use-state-if-mounted#5]
Hi there!

A suggestion is to use `useCallback` to preserve the identity of the `newSetState` function, so that `newSetState` can be used in optimized child components that may choose not to re-render based on prop changes.

This will work as `setState` itself keeps its identity (see [Note](https://reactjs.org/docs/hooks-reference.html#usestate)), and as long as `isComponentMounted` remains a ref the function doesn't need to change, as the function will always have access to the ref's current value.

```
import { useState, useCallback } from 'react';
import useIsComponentMounted from './useIsComponentMounted';

export default function useStateIfMounted(initialValue) {

  const isComponentMounted = useIsComponentMounted();
  const [state, setState] = useState(initialValue);

  const newSetState = useCallback((value) => {
    if (isComponentMounted.current) {
      setState(value);
    }
  });

  return [state, newSetState];
}
```

**Comment by Angelfire** [comment]
@Colkadome You forgot the `useCallback` dependencies:
```js
export default function useStateIfMounted(initialValue) {
  const isComponentMounted = useIsComponentMounted();
  const [state, setState] = useState(initialValue);

  const newSetState = useCallback((value) => {
    if (isComponentMounted.current) {
      setState(value);
    }
  }, [isComponentMounted]);

  return [state, newSetState];
}
```
